// Ensure 'cmd' is properly defined in your project
const { cmd } = require('../command'); 
const axios = require('axios'); // Make sure axios is installed: npm install axios

// --- Configuration for the new hypothetical API ---
// IMPORTANT: REPLACE THESE WITH YOUR ACTUAL API DETAILS
const NEW_NSFW_API_BASE_URL = 'https://your-new-awesome-nsfw-api.com/api/v1/images'; // Replace with the actual base URL of your chosen API
const NEW_NSFW_API_KEY = 'YOUR_API_KEY_HERE'; // Replace with your actual API Key!

// --- Utility function to fetch image from the new API ---
// This function centralises the API call logic.
async function fetchNsfwImage(category, replyFunction) {
    try {
        // Construct the API URL. Adjust 'type' to match the new API's parameter name.
        const apiUrl = `${NEW_NSFW_API_BASE_URL}?type=${category}&key=${NEW_NSFW_API_KEY}`;
        
        const response = await axios.get(apiUrl);

        // Adjust 'response.data.url' to match where the image URL is located in the new API's response
        if (response.data && response.data.url) { 
            return response.data.url;
        } else {
            await replyFunction(`❌ No image found for category: ${category}. The API might not support this specific type, or the response format is unexpected.`);
            return null;
        }
    } catch (e) {
        console.error(`Error fetching ${category} image:`, e);
        await replyFunction('❌ An error occurred whilst fetching the image. The API might be down, or your API key is incorrect/invalid.');
        return null;
    }
}

// --- COMMAND: nsfw (displays menu) ---
cmd({
    pattern: "nsfw", // Command name
    desc: "Display a list of NSFW options",
    category: "fun",
    use: '.nsfw',
    react: "🔥", // Reaction added
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    try {
        // List of NSFW options
        const nsfwList = `
   *❦ \`SHADOW-XTECH SEX HUB.🎀🍭\`*

1️⃣ *EJACULATION💦*
2️⃣ *PENIS🍆*
3️⃣ *EREC🌭*
4️⃣ *NUDE🍜*
5️⃣ *SEX🫦*
6️⃣ *CUTE🩷*
7️⃣ *ORGASM🌊*
8️⃣ *ANAL🕳️*
9️⃣ *SUSPENSION🍑*
🔟 *KISS💋*

────────────────
*_Simply type the number corresponding to the option you'd like to choose._*
────────────────
⚠️\`[NOTICE]\` 
*By continuing you agree that you are 18+ .*`;

        // Image URL for NSFW menu
        const imageUrl = 'https://files.catbox.moe/78nvv0.jpg';

        // Sending the list with the image and caption
        await conn.sendMessage(from, {
            text: nsfwList,
            caption: 'Choose one from the list above!',
            image: { url: imageUrl }
        }, { quoted: mek });
    } catch (e) {
        console.error(e);
        reply('❌ An error occurred whilst processing your request.');
    }
});

// --- COMMAND: ejaculation ---
cmd({
    pattern: "ejaculation", // Command name
    desc: "Fetch an NSFW image related to ejaculation",
    category: "fun",
    use: '.ejaculation',
    react: "🔥",
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Pass the exact category string that the new API expects for 'ejaculation'
    const imageUrl = await fetchNsfwImage('ejaculation', reply); 
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: `Here's your ${command} image 🔞🍆🍑.\n> © Generated by Nasty Shadow-Xtech😋🍑🔞.`,
        }, { quoted: mek });
    }
});

// --- COMMAND: penis ---
cmd({
    pattern: "penis", // Command name
    desc: "Fetch an NSFW image related to penises",
    category: "fun",
    use: '.penis',
    react: "🍑",
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Adjust 'penis_under_skirt' to the new API's exact category for penis images
    const imageUrl = await fetchNsfwImage('penis_under_skirt', reply); 
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: `Here's your ${command} image 🔞🍆🍑.\n> © Generated by Nasty Shadow-Xtech😋🍑🔞.`,
        }, { quoted: mek });
    }
});

// --- COMMAND: erec ---
cmd({
    pattern: "erec", // Command name
    desc: "Fetch an NSFW image related to erect nipples",
    category: "fun",
    use: '.erec',
    react: "🍑",
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Adjust 'erect_nipple' to the new API's exact category for erect images
    const imageUrl = await fetchNsfwImage('erect_nipple', reply); 
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: `Here's your ${command} image 🔞🍆🍑.\n> © Generated by Nasty Shadow-Xtech😋🍑🔞.`,
        }, { quoted: mek });
    }
});

// --- COMMAND: nude ---
cmd({
    pattern: "nude", // Command name
    desc: "Display a nude NSFW image",
    category: "fun",
    use: '.nude',
    react: "🔥", // Reaction added
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Adjust 'nude' to the new API's exact category for nude images
    const imageUrl = await fetchNsfwImage('nude', reply);
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: 'Here is your nude NSFW image 🔞🔥.\n> © Generated by Nasty Shadow-Xtech 😋🔥🔞.'
        }, { quoted: mek });
    }
});

// --- COMMAND: sex ---
cmd({
    pattern: "sex", // Command name
    desc: "Display a NSFW sex image",
    category: "fun",
    use: '.sex',
    react: "🔥", // Reaction added
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Adjust 'sex' to the new API's exact category for sex images
    const imageUrl = await fetchNsfwImage('sex', reply);
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: 'Here is your sex NSFW image 🔞🔥.\n> © Generated by Nasty Shadow-Xtech😋🔥🔞.'
        }, { quoted: mek });
    }
});

// --- COMMAND: cute ---
cmd({
    pattern: "cute", // Command name
    desc: "Display a NSFW cute image",
    category: "fun",
    use: '.cute',
    react: "🌸", // Reaction added
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Adjust 'cute' to the new API's exact category for cute images
    const imageUrl = await fetchNsfwImage('cute', reply);
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: 'Here is your cute NSFW image 🔞💖.\n> © Generated by Nasty Shadow-Xtech😋💖🔞.'
        }, { quoted: mek });
    }
});

// --- COMMAND: orgasm ---
cmd({
    pattern: "orgasm", // Command name
    desc: "Display a NSFW orgasm image",
    category: "fun",
    use: '.orgasm',
    react: "💥", // Reaction added
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Adjust 'orgasm' to the new API's exact category for orgasm images
    const imageUrl = await fetchNsfwImage('orgasm', reply);
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: 'Here is your orgasm NSFW image 🔞💥.\n> © Generated by Nasty Shadow-Xtech😋💥🔞.'
        }, { quoted: mek });
    }
});

// --- COMMAND: anal ---
cmd({
    pattern: "anal", // Command name
    desc: "Display a NSFW anal image",
    category: "fun",
    use: '.anal',
    react: "🔥", // Reaction added
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Adjust 'anal_sex' to the new API's exact category for anal images
    const imageUrl = await fetchNsfwImage('anal_sex', reply); 
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: 'Here is your anal NSFW image 🔞🔥.\n> © Generated by Nasty Shadow-Xtech😋🔥🔞.'
        }, { quoted: mek });
    }
});

// --- COMMAND: suspension ---
cmd({
    pattern: "suspension", // Command name
    desc: "Display a NSFW suspension image",
    category: "fun",
    use: '.suspension',
    react: "🔥", // Reaction added
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Adjust 'suspension' to the new API's exact category for suspension images
    const imageUrl = await fetchNsfwImage('suspension', reply);
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: 'Here is your suspension NSFW image 🔞🔥.\n> © Generated by Nasty Shadow-Xtech 😋🔥🔞.'
        }, { quoted: mek });
    }
});

// --- COMMAND: kiss ---
cmd({
    pattern: "kiss", // Command name
    desc: "Display a NSFW kissing image",
    category: "fun",
    use: '.kiss',
    react: "💋", // Reaction added
    filename: __filename
},
async (conn, mek, m, { from, l, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    // Adjust 'kissing_while_penetrated' to the new API's exact category for kissing images
    const imageUrl = await fetchNsfwImage('kissing_while_penetrated', reply); 
    if (imageUrl) {
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: 'Here is your kiss NSFW image 🔞💋.\n> © Generated by Nasty Shadow-Xtech 😋💋🔞.'
        }, { quoted: mek });
    }
});
